Test case :- From the given data Wbc.csv we need to predict the presenence of cancer

Information about the data :-  

This csv file contains test report on different white blood cells based on that test predict cancer is present or not

**step1 Import Necessary libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("wbc.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

**EDA**

In [ ]:
#check the rows and columnb
df.shape

(569, 33)

In [ ]:
#check the data types
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
Unnamed: 32                float64
dtype: object

In [ ]:
#get the descriptive stats of the data
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [ ]:
#check the column
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

*From the above command i can see 2 columns are un related columns

1. id :- patient id --> we are nothing to do with patient id means we wont apply any arthematic operations so i am dropping the column


2. UnNamed column :-  all are null values in the column  so drop the column

In [ ]:
#check the null values
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [ ]:
#check the duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop(columns="id",inplace=True)
df.shape

(569, 32)

In [ ]:
df.drop(columns = "Unnamed: 32",inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

from the data we can see "diagnosis" is the target variable

check the unique value sin the diagnosis

In [ ]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [ ]:
#check the distribution of the data inthe diagnosis
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
df.shape

(569, 31)

**define the features and target varible**

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
x = df.loc[:,df.columns[1:]]
y = df['diagnosis']
#In column diagnosis "M" and "B" is a categorical data convert in to numbers
#replace M--> 1   and B --> 0
#to replace the data in pandas dataframe use "pd.map()"
y = y.map({'M':1,'B':0})

**split the data**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=7)

**Scale the data**

In [ ]:
from sklearn.preprocessing import StandardScaler
#initialise the model
scaler = StandardScaler()
#fit the data
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

2nd Task jar : supervised learning

3rd Model jar :- Binary tree structure ,

to ask the right question use the entropy --> measure of randomness

In [ ]:
from sklearn.tree import DecisionTreeClassifier
#intalize
dt = DecisionTreeClassifier()
# fit train data
dt.fit(x_train,y_train) # loss automatticaly calculated

DecisionTreeClassifier()

In [ ]:
# predict the model
y_pred = dt.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

**evaluate the model**

In [ ]:
from sklearn.metrics import accuracy_score , f1_score
acc_dt = accuracy_score(y_test,y_pred)
f1_dt = f1_score(y_test,y_pred)
print("accuracy score of dt:",acc_dt)
print("f1 score of dt:",f1_dt)

accuracy score of dt: 0.916083916083916
f1 score of dt: 0.8571428571428571

**to find the maximum depth use the Hit and trail method***

In [ ]:
from sklearn.model_selection import cross_val_score

for depth in [1,2,3,4,5,6,7,8,9,10,20]:
  dt = DecisionTreeClassifier(max_depth=depth)
  dt = dt.fit(x_train,y_train)
  train_accuracy = dt.score(x_train,y_train)
  val_accuracy = cross_val_score(dt,x_train,y_train,cv=10)
  print("depth:",depth,"training-accuracy:",train_accuracy,"cross_val_score:",np.mean(val_accuracy))

depth: 1 training-accuracy: 0.9248826291079812 cross_val_score: 0.9061461794019934
depth: 2 training-accuracy: 0.9483568075117371 cross_val_score: 0.9250830564784053
depth: 3 training-accuracy: 0.9694835680751174 cross_val_score: 0.9223698781838318
depth: 4 training-accuracy: 0.9859154929577465 cross_val_score: 0.9248062015503876
depth: 5 training-accuracy: 0.9929577464788732 cross_val_score: 0.9246954595791805
depth: 6 training-accuracy: 0.9953051643192489 cross_val_score: 0.9295127353266889
depth: 7 training-accuracy: 1.0 cross_val_score: 0.931672203765227
depth: 8 training-accuracy: 1.0 cross_val_score: 0.915171650055371
depth: 9 training-accuracy: 1.0 cross_val_score: 0.9292912513842746
depth: 10 training-accuracy: 1.0 cross_val_score: 0.9270210409745294
depth: 20 training-accuracy: 1.0 cross_val_score: 0.9129568106312294

The best maximu depth for DT is '5'

again i'll train the model by using max depth to reduce the over fitting

In [ ]:
from sklearn.tree import DecisionTreeClassifier
#intialize the model
dt = DecisionTreeClassifier(max_depth=5)
#fit the training data
dt.fit(x_train,y_train) #loss automatically caluculated
#predict on test data
y_pred=dt.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score,f1_score
acc_dt = accuracy_score(y_test,y_pred)
f1_dt = f1_score(y_test,y_pred)
print(acc_dt)
print(f1_dt)

0.8951048951048951
0.8235294117647058

**feature importence**

In [ ]:
df.shape

(569, 31)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
#intialize the model
dt = DecisionTreeClassifier(criterion='gini',max_depth=6)
#fit the training data
dt.fit(x_train,y_train) #loss automatically caluculated
importance = dt.feature_importances_
list(zip(importance,x_test.columns))

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

**plot the tree**

In [ ]:
from sklearn import tree

plt.figure(figsize=(20,10))
tree.plot_tree(dt,filled=True,rounded=True,feature_names=x_train.columns,class_names=True,fontsize=10)
# gini measure of impurity of randomness

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

apply logistic regression

apply KNN classifiers

find the best model by evaluating

and write final report on those models

**logistic regression**

**split data**

In [ ]:
x = df.loc[:,df.columns[1:]]
y = df['diagnosis']
#In column diagnosis "M" and "B" is a categorical data convert in to numbers
#replace M--> 1   and B --> 0
#to replace the data in pandas dataframe use "pd.map()"
y = y.map({'M':1,'B':0})

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=7)

**import logistic regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

#intalize model
regresor = LogisticRegression()
#train the model on train data
regresor.fit(x_train,y_train)

**predict the model on test data**

In [ ]:
y_pred = regresor.predict(x_test)

**evaluate the model**

In [ ]:
from sklearn.metrics import accuracy_score,f1_score

acc_logr = accuracy_score(y_test,y_pred)
f1_logr = f1_score(y_test,y_pred)

print("accuracy score:",acc_logr)
print("f1 score:",f1_logr)

**KNN classifier**

**split the data**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=7)

**scale the data**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

**import knn classifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

**predict the model**

In [ ]:
y_pred = knn.predict(x_test)
y_pred

**evaluate the model**

In [ ]:
from sklearn.metrics import accuracy_score , f1_score

acc_knn = accuracy_score(y_test,y_pred)
f1_knn = f1_score(y_test,y_pred)

print("accuracy score:",acc_knn)
print("f1 score:",f1_knn)

accuracy score: 0.8951048951048951
f1 score: 0.8235294117647058

**cross validation score for knn to find best k value**

In [ ]:
from sklearn.model_selection import cross_val_score # it is a smart way of spliting
from sklearn.neighbors import KNeighborsClassifier
for i in [1,2,3,4,5,6,7,8,9,10,20,30]:
  #intialize the model
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(x_train,y_train)
  # validate the model to find the best value of "k" for thAT WE USE cross_val_score use only on training data
  train_score = knn.score(x_train,y_train)
  val_score = cross_val_score(knn,x_train,y_train,cv=10)
  print("kvalue",i,"train_score",train_score,"cv_score:",np.mean(val_score))

kvalue 1 train_score 1.0 cv_score: 0.9391472868217055
kvalue 2 train_score 0.971830985915493 cv_score: 0.9531007751937984
kvalue 3 train_score 0.9765258215962441 cv_score: 0.9648947951273532
kvalue 4 train_score 0.9741784037558685 cv_score: 0.9602436323366556
kvalue 5 train_score 0.971830985915493 cv_score: 0.9578626799557032
kvalue 6 train_score 0.9694835680751174 cv_score: 0.9532115171650055
kvalue 7 train_score 0.9694835680751174 cv_score: 0.9579734219269103
kvalue 8 train_score 0.9671361502347418 cv_score: 0.9602436323366556
kvalue 9 train_score 0.971830985915493 cv_score: 0.9601882613510521
kvalue 10 train_score 0.9694835680751174 cv_score: 0.9531007751937984
kvalue 20 train_score 0.9624413145539906 cv_score: 0.9532115171650055
kvalue 30 train_score 0.9577464788732394 cv_score: 0.9532115171650055

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_jobs=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_jobs=3)

**again evalluate the model**

In [ ]:
acc_knn = accuracy_score(y_test,y_pred)
f1_knn = f1_score(y_test,y_pred)

print("accuracy score:",acc_knn)
print("f1 score:",f1_knn)

accuracy score: 0.8951048951048951
f1 score: 0.8235294117647058

In [ ]:
print("==========================================================================")
print("\n")
print("evaluation metrics of Dt , logr and knn")

print("accuracy score of DT:",acc_dt)
print("f1 score of DT:",f1_dt)
print("\n")

print("accuracy score of logr:",acc_logr)
print("f1 score of logr:",f1_logr)
print("\n")

print("accuracy score of KNN:",acc_knn)
print("f1 score of KNN:",f1_knn)

==========================================================================


evaluation metrics of Dt , logr and knn
accuracy score of DT: 0.8951048951048951
f1 score of DT: 0.8235294117647058

NameError: name 'acc_logr' is not defined